name: koppeltaal_2_docker_compose
services:
  postgres:
    image: postgres:14.7-alpine
    restart: always
    env_file:
      - ./config/.db-env
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/data/postgres
      - ./sql/create_databases.sql:/docker-entrypoint-initdb.d/create_databases.sql
    storage_opt:
      size: '512M'
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    volumes:
      - ./config/keycloak-kt2-realm.json:/opt/keycloak/data/import/keycloak-kt2-realm.json
    command:
      - start-dev --import-realm
    env_file:
      - config/.keycloak-env
    ports:
      - '9990:9990'
      - '8080:8080'
    restart: on-failure:10

  domain-admin:
    image: jorisheadease/kt2-domain-admin:latest
    ports:
      - '8081:8080'
    env_file:
      - ./config/.domain-admin-env
    restart: on-failure:10
#
#  auth-service:
#    image: jorisheadease/kt2-auth-service
#    env_file:
#      - ./config/.auth-service-env
#    ports:
#      - '8083:5000'

#  fhir-service:
#    image: jorisheadease/hapi:master-tomcat
#    env_file:
#      - ./config/.fhir-service-env
#    ports:
#      -

volumes:
  postgres-data:
    driver: local
